# Generated by Django 5.2.14 on 2026-05-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地域名')),
                ('prefecture', models.CharField(max_length=50, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='市区町村')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '地域',
                'verbose_name_plural': '地域',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='カテゴリ名')),
                ('slug', models.SlugField(help_text='URLや内部識別に使う半角英数字、ハイフン、アンダースコアを入力してください。', max_length=120, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '観光カテゴリ',
                'verbose_name_plural': '観光カテゴリ',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='スポット名')),
                ('slug', models.SlugField(help_text='URLや内部識別に使う半角英数字、ハイフン、アンダースコアを入力してください。', max_length=180, unique=True, verbose_name='スラッグ')),
                ('short_description', models.CharField(blank=True, help_text='一覧表示やAIへの短い説明に使います。', max_length=255, verbose_name='短い説明')),
                ('description', models.TextField(blank=True, verbose_name='詳細説明')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='経度')),
                ('estimated_stay_minutes', models.PositiveIntegerField(default=60, help_text='観光スポットでの滞在目安時間を分単位で入力してください。', verbose_name='滞在目安時間')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='営業時間')),
                ('closed_days', models.CharField(blank=True, max_length=255, verbose_name='定休日')),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='予算下限')),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='予算上限')),
                ('official_url', models.URLField(blank=True, verbose_name='公式URL')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google Maps URL')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='電話番号')),
                ('recommended_season', models.CharField(blank=True, max_length=100, verbose_name='おすすめ時期')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='タグ')),
                ('is_rainy_day_friendly', models.BooleanField(default=False, verbose_name='雨の日向け')),
                ('is_family_friendly', models.BooleanField(default=False, verbose_name='子連れ向け')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='spots.spotcategory', verbose_name='カテゴリ')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spots', to='spots.region', verbose_name='地域')),
            ],
            options={
                'verbose_name': '観光スポット',
                'verbose_name_plural': '観光スポット',
                'ordering': ['name'],
            },
        ),
    ]
