services:
  db:
    image: postgres:16
    container_name: localtrip_postgres
    environment:
      POSTGRES_DB: localtrip_db
      POSTGRES_USER: localtrip_user
      POSTGRES_PASSWORD: localtrip_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
