# Generated by Django 5.2.14 on 2026-05-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelPlanRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150, verbose_name="プラン名")),
                (
                    "days",
                    models.CharField(
                        choices=[
                            ("half_day", "半日"),
                            ("one_day", "1日"),
                            ("two_days", "1泊2日"),
                            ("three_days", "2泊3日"),
                        ],
                        max_length=20,
                        verbose_name="旅行日数",
                    ),
                ),
                (
                    "transportation",
                    models.CharField(
                        choices=[
                            ("car", "車"),
                            ("walk", "徒歩"),
                            ("public_transport", "公共交通機関"),
                            ("bicycle", "自転車"),
                        ],
                        max_length=20,
                        verbose_name="移動手段",
                    ),
                ),
                ("budget_min", models.PositiveIntegerField(blank=True, null=True, verbose_name="予算下限")),
                ("budget_max", models.PositiveIntegerField(blank=True, null=True, verbose_name="予算上限")),
                (
                    "traveler_type",
                    models.CharField(
                        choices=[
                            ("solo", "一人旅"),
                            ("couple", "カップル"),
                            ("family", "家族旅行"),
                            ("senior", "シニア"),
                            ("friends", "友人同士"),
                            ("business", "出張ついで"),
                        ],
                        max_length=30,
                        verbose_name="旅行者タイプ",
                    ),
                ),
                ("is_rainy_day", models.BooleanField(default=False, verbose_name="雨の日を想定")),
                ("is_family_friendly", models.BooleanField(default=False, verbose_name="子連れ向けを優先")),
                (
                    "free_text",
                    models.TextField(
                        blank=True,
                        help_text="旅行者の希望や補足条件を入力してください。",
                        verbose_name="自由入力",
                    ),
                ),
                (
                    "candidate_spots_snapshot",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="プラン作成時点の候補スポット情報を保存します。",
                        verbose_name="候補スポットスナップショット",
                    ),
                ),
                (
                    "ai_prompt_preview",
                    models.TextField(
                        blank=True,
                        help_text="AIに渡す予定のプロンプト下書きです。",
                        verbose_name="AIプロンプト下書き",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="plan_requests",
                        to="spots.spotcategory",
                        verbose_name="興味のあるカテゴリ",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_requests",
                        to="spots.region",
                        verbose_name="地域",
                    ),
                ),
            ],
            options={
                "verbose_name": "旅行プラン作成依頼",
                "verbose_name_plural": "旅行プラン作成依頼",
                "ordering": ["-created_at"],
            },
        ),
    ]
